MySQL:
  Host: localhost
  Port: 3306
  Username: root
  Password: admin
  Database: VortalMC-Chat
Defaults:
  Channel: global
  Name-Color: '&7'
  Chat-Color: '&7'
  Prefix: 'none'
  Suffix: 'none'
  Nickname: 'none'
Channels:
  Global:
    Name: global
    Permission: vortalmcchat.channel.global
    Format: '${PREFIX}${DISPLAY_NAME}${SUFFIX} &8» ${CHAT_COLOR}${MESSAGE}'
    Scope: global
    Aliases:
    - 'g'
  Staff:
    Name: staff
    Permission: vortalmcchat.channel.staff
    Format: '&c&lSC &7${CHAT_COLOR}${NICKNAME} &8» ${CHAT_COLOR}${MESSAGE}'
    Scope: global
    Aliases:
    - 'sc'
  Local:
    Name: local
    Permission: vortalmcchat.channel.local
    Format: '&c[L] &r${PREFIX}${DISPLAY_NAME}${SUFFIX} &8» ${CHAT_COLOR}${MESSAGE}'
    Scope: local
    Aliases:
    - 'l'
Messages:
  Response-Method: LAST_MESSAGE_SENDER
Nickname:
  Minimum-Length: 3
  Maximum-Length: 25
  Forbidden-Text:
  - '.'
  - ','
  - ''''
  - '"'
  - '^'
  - '-'
  - '~'
  - '&0'
Prefix:
  Minimum-Length: 3
  Maximum-Length: 25
  Forbidden-Text:
  - '.'
  - ','
  - ''''
  - '"'
  - '^'
  - '-'
  - '~'
  - '&0'
Suffix:
  Minimum-Length: 3
  Maximum-Length: 25
  Forbidden-Text:
  - '.'
  - ','
  - ''''
  - '"'
  - '^'
  - '-'
  - '~'
  - '&0'
Name-Color:
  Forbidden-Colors:
  - '&0'
Chat-Color:
  Forbidden-Colors:
  - '&0'