MySQL:
  Host: localhost
  Port: 3306
  Username: root
  Password: admin
  Database: VortalMC-Chat
Defaults:
  Channel: global
  Name-Color: '&7'
  Chat-Color: '&7'
  Prefix: 'none'
  Suffix: 'none'
  Nickname: 'none'
  Enable-Messages: true
  Enable-Chat: true
Channels:
  Global:
    Name: global
    Permission: vortalmcchat.channel.global
    Format: '&r${PREFIX}${DISPLAY_NAME}&r${SUFFIX} &8» ${CHAT_COLOR}${MESSAGE}'
    Scope: global
    Aliases:
    - 'g'
  Staff:
    Name: staff
    Permission: vortalmcchat.channel.staff
    Format: '&c&lSC &7${CHAT_COLOR}${NICKNAME} &8» ${CHAT_COLOR}${MESSAGE}'
    Scope: global
    Aliases:
    - 'sc'
  Local:
    Name: local
    Permission: vortalmcchat.channel.local
    Format: '&c[L] &r${PREFIX}${DISPLAY_NAME}&r${SUFFIX} &8» ${CHAT_COLOR}${MESSAGE}'
    Scope: local
    Aliases:
    - 'l'
Messages:
  Response-Method: LAST_MESSAGE_SENDER
Nickname:
  Minimum-Length: 3
  Maximum-Length: 25
  Forbidden-Text:
  - '.'
  - ','
  - ''''
  - '"'
  - '^'
  - '-'
  - '~'
  - '&0'
Prefix:
  Minimum-Length: 3
  Maximum-Length: 25
  Forbidden-Text:
  - '.'
  - ','
  - ''''
  - '"'
  - '^'
  - '-'
  - '~'
  - '&0'
Suffix:
  Minimum-Length: 3
  Maximum-Length: 25
  Forbidden-Text:
  - '.'
  - ','
  - ''''
  - '"'
  - '^'
  - '-'
  - '~'
  - '&0'
Name-Color:
  Allowed-Colors:
  - '&1'
  - '&2'
  - '&3'
  - '&4'
  - '&5'
  - '&6'
  - '&7'
  - '&9'
  - '&a'
  - '&b'
  - '&c'
  - '&d'
  - '&e'
  - '&f'
Chat-Color:
  Allowed-Colors:
  - '&1'
  - '&2'
  - '&3'
  - '&4'
  - '&5'
  - '&6'
  - '&7'
  - '&9'
  - '&a'
  - '&b'
  - '&c'
  - '&d'
  - '&e'
  - '&f'