MySQL:
  Host: localhost
  Port: 3306
  Username: root
  Password: admin
  Database: VortalMC-Chat
Defaults:
  Channel: global
  Name-Color: '&7'
  Chat-Color: '&7'
  Prefix: 'none'
  Suffix: 'none'
  Nickname: 'none'
Channels:
  Global:
    Name: global
    Permission: vortalmcchat.channel.global
    Format: '${PREFIX}${DISPLAY_NAME}${SUFFIX} &8» ${CHAT_COLOR}${MESSAGE}'
    Scope: global
  Staff:
    Name: staff
    Permission: vortalmcchat.channel.staff
    Format: '&c&lSC ${NICKNAME} &8» ${CHAT_COLOR}${MESSAGE}'
    Scope: global
  Local:
    Name: local
    Permission: vortalmcchat.channel.local
    Format: '&c[L] &r${PREFIX}${DISPLAY_NAME}${SUFFIX} &8» ${CHAT_COLOR}${MESSAGE}'
    Scope: local